In [175]:
import pandas as pd
import numpy as np
df = pd.read_csv('/workspaces/Python-For-Data-Science/Database from Kaggle/dirty_cafe_sales.csv')

In [176]:
df.shape # the size of the index are 10000 followed by 8 columns

(10000, 8)

In [177]:
df.head(20)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,ERROR,2,1.5,3.0,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.0,Cash,ERROR,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.0,Cash,Takeaway,2023-01-15

In [178]:
df['Item'].hasnans # ok in our dataset there are several NaN values in our items columns

True

In [179]:
df[df['Item'].isnull()].count() # now we counted all values which are null in database.

Transaction ID      333
Item                  0
Quantity            330
Price Per Unit      326
Total Spent         329
Payment Method      251
Location            229
Transaction Date    327
dtype: int64

In [180]:
df[df['Item'].notnull()].count()

Transaction ID      9667
Item                9667
Quantity            9532
Price Per Unit      9495
Total Spent         9498
Payment Method      7170
Location            6506
Transaction Date    9514
dtype: int64

In [181]:
df.shape # sorry woh experiment toh khoob mare but fr socha sab NaN uda deta hu kya hi hoga

(10000, 8)

In [182]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [183]:
bringmeback = {
    1.0 : "Cookie",
    2.0 : "Coffee",
    3.0 : "Cake",
    4.0 : "Smoothie",
    5.0 : "Salad"
}

In [184]:

df['Item'] = df['Item'].fillna(df['Price Per Unit'].map(bringmeback))

df.shape # so this is our cleaned data

(10000, 8)

In [185]:
df.shape

(10000, 8)

In [186]:
# lets check that how many number of NaN and ERROR values in Quantity
df[df['Quantity']=='ERROR']

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
20,TXN_3522028,Smoothie,ERROR,4.0,20.0,Cash,In-store,2023-04-04
55,TXN_5522862,Cookie,ERROR,1.0,2.0,Credit Card,Takeaway,2023-03-19
117,TXN_2148617,Juice,ERROR,3.0,9.0,Digital Wallet,UNKNOWN,2023-01-10
177,TXN_1896955,Salad,ERROR,5.0,25.0,NaN,In-store,2023-09-23
178,TXN_5075974,Smoothie,ERROR,4.0,16.0,Digital Wallet,NaN,2023-04-11
...,...,...,...,...,...,...,...,...
9832,TXN_3325234,Tea,ERROR,1.5,1.5,ERROR,In-store,2023-08-26
9846,TXN_7621213,Coffee,ERROR,2.0,6.0,NaN,In-store,2023-03-07
9911,TXN_2464054,Coffee,ERROR,2.0,10.0,NaN,Takeaway,2023-08-18
9935,TXN_9778251,Tea,ERROR,1.5,6.0,NaN,Takeaway,2023-11-09
9957,TXN_6487003,Coffee,ERROR,2.0,8.0,Credit Card,Takeaway,2023-11-15

In [187]:
df['Quantity'] = df['Quantity'].replace(['ERROR', 'UNKNOWN'], np.nan)
df['Total Spent'] = df['Total Spent'].replace(['ERROR', 'UNKNOWN'], np.nan)
df['Price Per Unit'] = df['Price Per Unit'].replace(['ERROR', 'UNKNOWN'], np.nan)



df['Quantity'] = pd.to_numeric(df['Quantity'])
df['Total Spent'] = pd.to_numeric(df['Total Spent'])
df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'])


df['Quantity'] = df['Quantity'].fillna(df['Total Spent'] / df['Price Per Unit'])

df.head(30)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3.0,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5.0,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5.0,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,ERROR,2.0,1.5,3.0,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1.0,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5.0,3.0,15.0,Cash,ERROR,2023-03-25
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,5.0,4.0,20.0,Cash,In-store,2023-04-04
21,TXN_3567645,Smoothie,4.0,4.0,16.0,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3.0,4.0,12.0,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2.0,4.0,8.0,NaN,NaN,2023-09-18
24,TXN_9400181,Sandwich,5.0,4.0,20.0,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3.0,4.0,NaN,UNKNOWN,UNKNOWN,2023-12-13
26,TXN_5183041,Cookie,5.0,1.0,5.0,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4.0,3.0,12.0,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-11
29,TXN_7640952,Cake,4.0,3.0,12.0,Digital Wallet,Takeaway,ERROR

In [188]:
df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Total Spent'] / df['Quantity'])
df['Total Spent'] = df['Total Spent'].fillna(df['Price Per Unit'] / df['Quantity'])


df.tail(40)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9960,TXN_3546629,Juice,5.0,3.0,15.0,NaN,In-store,2023-03-04
9961,TXN_2153100,Tea,2.0,1.5,3.0,Cash,NaN,2023-12-29
9962,TXN_4723089,Sandwich,4.0,4.0,16.0,Cash,In-store,2023-05-23
9963,TXN_8545707,Cake,5.0,3.0,15.0,NaN,Takeaway,2023-02-14
9964,TXN_8938445,Cake,3.0,3.0,9.0,NaN,In-store,2023-11-07
9965,TXN_5846013,Tea,2.0,1.5,3.0,Digital Wallet,NaN,2023-12-20
9966,TXN_6494265,Coffee,2.0,2.0,4.0,NaN,NaN,2023-05-24
9967,TXN_8563793,Juice,4.0,3.0,12.0,NaN,In-store,2023-03-26
9968,TXN_8866974,Smoothie,3.0,4.0,12.0,Digital Wallet,Takeaway,2023-03-14
9969,TXN_9954652,Coffee,2.0,2.0,4.0,Cash,In-store,2023-09-12
9970,TXN_5762440,Sandwich,5.0,4.0,20.0,Cash,In-store,2023-03-05
9971,TXN_6120851,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-02-04
9972,TXN_3124078,Cake,4.0,3.0,12.0,UNKNOWN,In-store,2023-08-06
9973,TXN_7936002,Salad,2.0,5.0,10.0,Digital Wallet,NaN,2023-01-26
9974,TXN_8076061,Tea,4.0,1.5,6.0,Cash,In-store,2023-04-01
9975,TXN_9668108,Cake,1.0,3.0,3.0,Cash,In-store,2023-01-20
9976,TXN_3528020,Cookie,1.0,1.0,1.0,NaN,Takeaway,2023-08-26
9977,TXN_5548914,Juice,2.0,3.0,1.5,Digital Wallet,In-store,2023-11-04
9978,TXN_4302199,Tea,3.0,1.5,4.5,NaN,NaN,2023-02-16
9979,TXN_9933628,Smoothie,5.0,4.0,20.0,Cash,In-store,2023-07-20
9980,TXN_6796890,Tea,4.0,1.5,6.0,UNKNOWN,NaN,2023-08-24
9981,TXN_4583012,ERROR,5.0,4.0,20.0,Digital Wallet,NaN,2023-02-27
9982,TXN_8567525,Cookie,2.0,1.0,2.0,NaN,Takeaway,2023-12-30
9983,TXN_9226047,Smoothie,3.0,4.0,12.0,Cash,NaN,UNKNOWN
9984,TXN_3142496,Smoothie,1.0,4.0,4.0,Cash,Takeaway,2023-07-27
9985,TXN_3297457,Cake,2.0,3.0,6.0,NaN,UNKNOWN,2023-01-03
9986,TXN_2858441,Sandwich,2.0,4.0,8.0,Credit Card,In-store,2023-12-14
9987,TXN_1784478,Juice,5.0,3.0,15.0,Cash,NaN,2023-07-31
9988,TXN_9594133,Cake,5.0,3.0,0.6,ERROR,NaN,NaN
9989,TXN_1741685,Juice,5.0,3.0,15.0,Cash,NaN,2023-08-18
9990,TXN_1538510,Coffee,5.0,2.0,10.0,Digital Wallet,NaN,2023-05-22
9991,TXN_3897619,Sandwich,3.0,4.0,12.0,Cash,Takeaway,2023-02-24
9992,TXN_2739140,Smoothie,4.0,4.0,16.0,UNKNOWN,In-store,2023-07-05
9993,TXN_4766549,Smoothie,2.0,4.0,2.0,Cash,NaN,2023-10-20
9994,TXN_7851634,UNKNOWN,4.0,4.0,16.0,NaN,NaN,2023-01-08
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3.0,1.0,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07