In [74]:
import pandas as pd

std = pd.read_csv('/content/StudentsPerformance.csv')
std.head(30)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
16,male,group C,high school,standard,none,88,89,86
17,female,group B,some high school,free/reduced,none,18,32,28
18,male,group C,master's degree,free/reduced,completed,46,42,46
19,female,group C,associate's degree,free/reduced,none,54,58,61
20,male,group D,high school,standard,none,66,69,63
21,female,group B,some college,free/reduced,completed,65,75,70
22,male,group D,some college,standard,none,44,54,53
23,female,group C,some high school,standard,none,69,73,73
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
25,male,group A,master's degree,free/reduced,none,73,74,72
26,male,group B,some college,standard,none,69,54,55
27,female,group C,bachelor's degree,standard,none,67,69,75
28,male,group C,high school,standard,none,70,70,65
29,female,group D,master's degree,standard,none,62,70,75

In [75]:
std.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [76]:
std = std.rename(columns={
    "race/ethnicity":"race",
    "parental level of education" : "edu_level",
    "test preparation course" : "test_prep",
    "math score" :"math",
    "reading score" : "reading",
    "writing score" : "writing"

})


std

,gender,race,edu_level,lunch,test_prep,math,reading,writing
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [91]:
def average_score(std):
  add = (std['writing'] + std['math'] + std['reading'])
  ans = add / 3
  return ans

In [95]:
std['average_score'] = std.apply(average_score, axis=1)
std['average_score']  = pd.to_numeric(std['average_score'])
std['average_score'] = std['average_score'].round(2)
std

,gender,race,edu_level,lunch,test_prep,math,reading,writing,average_score
0,female,group B,bachelor's degree,standard,none,72,72,74,72.67
1,female,group C,some college,standard,completed,69,90,88,82.33
2,female,group B,master's degree,standard,none,90,95,93,92.67
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.33
4,male,group C,some college,standard,none,76,78,75,76.33
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.00
996,male,group C,high school,free/reduced,none,62,55,55,57.33
997,female,group C,high school,free/reduced,completed,59,71,65,65.00
998,female,group D,some college,standard,completed,68,78,77,74.33
999,female,group D,some college,free/reduced,none,77,86,86,83.00

In [78]:
# std['average_score'] = (std['writing'] + std['math'] + std['reading']) / 3
std

,gender,race,edu_level,lunch,test_prep,math,reading,writing
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [96]:
none_std = std[std['test_prep']=="none"]
none_std.shape[0]
# ok so total number of none is 642

642

In [97]:
std.head()

,gender,race,edu_level,lunch,test_prep,math,reading,writing,average_score
0,female,group B,bachelor's degree,standard,none,72,72,74,72.67
1,female,group C,some college,standard,completed,69,90,88,82.33
2,female,group B,master's degree,standard,none,90,95,93,92.67
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.33
4,male,group C,some college,standard,none,76,78,75,76.33

In [102]:
none_std.groupby('race')['test_prep'].count().sort_values(ascending=False)

# so we find out that the group c have the most number of none prepare student.

race
group C    202
group D    180
group B    122
group E     80
group A     58
Name: test_prep, dtype: int64

In [105]:
none_std.groupby(['race','test_prep'])['average_score'].mean().sort_values(ascending=False)

# so the group E students who never prepare for the exam but give the highest number of score.

race     test_prep
group E  none         69.795375
group D  none         67.196278
group C  none         64.387574
group B  none         62.584918
group A  none         59.212069
Name: average_score, dtype: float64

In [107]:
std.head(30)

,gender,race,edu_level,lunch,test_prep,math,reading,writing,average_score
0,female,group B,bachelor's degree,standard,none,72,72,74,72.67
1,female,group C,some college,standard,completed,69,90,88,82.33
2,female,group B,master's degree,standard,none,90,95,93,92.67
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.33
4,male,group C,some college,standard,none,76,78,75,76.33
5,female,group B,associate's degree,standard,none,71,83,78,77.33
6,female,group B,some college,standard,completed,88,95,92,91.67
7,male,group B,some college,free/reduced,none,40,43,39,40.67
8,male,group D,high school,free/reduced,completed,64,64,67,65.00
9,female,group B,high school,free/reduced,none,38,60,50,49.33
10,male,group C,associate's degree,standard,none,58,54,52,54.67
11,male,group D,associate's degree,standard,none,40,52,43,45.00
12,female,group B,high school,standard,none,65,81,73,73.00
13,male,group A,some college,standard,completed,78,72,70,73.33
14,female,group A,master's degree,standard,none,50,53,58,53.67
15,female,group C,some high school,standard,none,69,75,78,74.00
16,male,group C,high school,standard,none,88,89,86,87.67
17,female,group B,some high school,free/reduced,none,18,32,28,26.00
18,male,group C,master's degree,free/reduced,completed,46,42,46,44.67
19,female,group C,associate's degree,free/reduced,none,54,58,61,57.67
20,male,group D,high school,standard,none,66,69,63,66.00
21,female,group B,some college,free/reduced,completed,65,75,70,70.00
22,male,group D,some college,standard,none,44,54,53,50.33
23,female,group C,some high school,standard,none,69,73,73,71.67
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,75.00
25,male,group A,master's degree,free/reduced,none,73,74,72,73.00
26,male,group B,some college,standard,none,69,54,55,59.33
27,female,group C,bachelor's degree,standard,none,67,69,75,70.33
28,male,group C,high school,standard,none,70,70,65,68.33
29,female,group D,master's degree,standard,none,62,70,75,69.00

In [128]:
def marks(score):
  if score >= 33:
    return "pass"
  else:
    return "fail"

In [159]:
std['final_result'] = std['average_score'].apply(marks)
std[std['final_result']=='pass'].groupby('gender').size()

gender
female    509
male      476
dtype: int64

In [161]:
male = std[(std['gender']=='male')&(std['final_result']=='pass')].count()
male

gender           476
race             476
edu_level        476
lunch            476
test_prep        476
math             476
reading          476
writing          476
average_score    476
final_result     476
dtype: int64

In [165]:
fmale = std[(std['gender']=='female')&(std['final_result']=='pass')].count()
fmale


# ye aise hi meri bakwas thi !

gender           509
race             509
edu_level        509
lunch            509
test_prep        509
math             509
reading          509
writing          509
average_score    509
final_result     509
dtype: int64

In [163]:
std.shape

(1000, 10)